<?php Load::lib("html") ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>Clases particulares Profesores particulares a domicilio madrid rivas</title>
<meta name="description" content="Clases particulares en Madrid. Clases de apoyo a domicilio en Madrid. Profesores particulares expertos en la ense&ntilde;anza en los 
										niveles de primaria, eso, bachillerato, selectividad, ingles y informatica." /> 
<meta name="keywords" content="clases particulares, clases particulares madrid, profesores particulares madrid, clases a domicilio madrid, clases de apoyo madrid, source, web, desarrollo web, desarrollo, clases madrid, clases, eso, refuerzos clases, tutores" /> 
<meta name="author" content="&amp;Source Ltda" /> 
<meta name="copyright" content="Copyright (c) &amp;Source Ltda." /> 
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />							<!-- CSS --> 
<link rel='stylesheet' type='text/css' href="vista/js/lib/css/qtip.css" /> 
<link rel='stylesheet' type='text/css' href="vista/css/weekcalendar/jquery.weekcalendar.css" /> 
<link rel='stylesheet' type='text/css' href="vista/css/demo.css"/> 
<link rel='stylesheet' type='text/css' href='vista/css/weekcalendar/skins/default.css' /> 
<link rel='stylesheet' type='text/css' href='vista/css/jquery.alerts.css' /> 
<link rel="stylesheet" href="vista/css/reset-tf.css" type="text/css" media="screen" /> 
<link rel="stylesheet" href="vista/css/multiselect/jquery.multiselect.css" type="text/css" media="screen" /> 
<link rel="stylesheet" href="vista/css/multiselect/jquery.multiselect.filter" type="text/css" media="screen" /> 

<?= View::partial("jquery",false,'template: ui-darkness'); ?>
 
<!-- Javascripts --> 
<script type='text/javascript' src='vista/js/lib/jquery.weekcalendar.js'></script> 
<script type='text/javascript' src="vista/js/lib/jquery.qtip-1.0.0-rc3.js"></script> 
<script type="text/javascript" src="vista/js/confPage.js"></script> 
<script type="text/javascript" src="vista/js/getBrowser.js"></script> 
<script type="text/javascript" src="vista/js/lib/facebox.js"></script> 
<script type="text/javascript" src="vista/js/lib/jquery.wysiwyg.js"></script> 
<script type="text/javascript" src="vista/js/lib/jquery.datePicker.js"></script> 
<script type="text/javascript" src="vista/js/lib/date.js"></script> 
<script type="text/javascript" src="vista/js/lib/jquery.alerts.js"></script> 
<script type="text/javascript" src="vista/js/lib/jquery.ddchart.js"></script> 
<script type="text/javascript" src="vista/js/lib/jquery.tooltip.js"></script> 
<script type="text/javascript" src="vista/js/lib/jquery.multiselect.js"></script> 
<script type="text/javascript" src="vista/js/lib/jquery.multiselect.filter.js"></script> 
 
 
<!--[if IE]><script language="javascript" type="text/javascript" src="vista/js/lib/excanvas.min.js"></script><![endif]--> 
<script language="javascript" type="text/javascript" src="vista/js/lib/jquery.flot.js"></script> 
 
 			<?= stylesheet_link_tag('pruebas/style') ?>
 			<?= javascript_include_tag('pruebas/configPage') ?>
		         
			<link rel="stylesheet" href="vista/css/invalid.css" type="text/css" media="screen" /> 
			<link href="vista/css/ddchart.css" rel="stylesheet" type="text/css" /> 
			<!--<link href="vista/css/master.css" rel="stylesheet" type="text/css" />   BEGIN Plugin Code --> 
		
</head> 
	<body> 
		<!-- Wrapper for the radial gradient background --> 
			<div id="sidebar">
				<div id="sidebar-wrapper"> <!-- Sidebar with logo and menu --> 
					<!-- Logo (221px wide) --> 
					<?= Html::link("a/a",Html::imagen("amecamx.png","Logotipo","id: logo")) ?>
					<!-- Sidebar Profile links -->
					<div id="profile">
						<table>
							<tr>
								<td rowspan="2">
									<img style="padding: 5px; background-color: #6BAE00" src="https://graph.facebook.com/906075301/picture" width="50px" alt="Ramiro" title="Ramiro" name="Ramiro" />	
								</td>
								<td id="username">Ramiro Alonso Vera Contreras</td>
							</tr>
							<tr>
								<td id="link">
									<?= Html::link("pruebas/link","Editar Perfil") ?>
								</td>
							</tr>
						</table>
					</div>
					
		            <script type="text/javascript"> 
					$(document).ready(function(){
						$("#Principal").addClass("current");
					});
					</script> 
					<ul id="main-nav">  <!-- Accordion Menu -->            
		    			<li> 
		                	<a href="#Contratacion" id="Contratacion" class="nav-top-item">Matriculas</a> 
		                	<ul> 
								<li><a href="index.php?controlador=ctrContrato&accion=verContrato">Ver/Descargar Contrato</a></li> 
		                    	<li><a href="index.php?controlador=ctrContrato&accion=listContratos">Lista de contratos</a></li> 
							</ul> 
						</li> 
			            <li> 
			                <a href="#" id="Facturacion" class="nav-top-item">Facturaci&oacute;n </a> 
			                <ul> 
								<li><a href="index.php?controlador=ctrFacturas&accion=verFactura">Ver/Descargar Factura</a></li> 
			                    <li><a href="index.php?controlador=ctrFacturas&accion=listFacturas">Lista de facturas</a></li> 
							</ul> 
						</li> 
			            <li> 
			            	<a href="#" id="Calendario" class="nav-top-item">Gestión de calendario</a> 
			            	<ul> 
			                    <li><a href="index.php?controlador=ctrCalendario&accion=verCalendario">Gestionar Calendarios</a></li> 
			                </ul> 
			            </li> 
			            <li> 
							<a href="#" id="Test" class="nav-top-item">Tests</a> 
			            	<ul> 
								<li><a href="index.php?controlador=ctrTest&accion=getIndexresulall">Ver resultados</a></li> 
			                </ul> 
			            </li> 
			            <li> 
			                <a href="#" id="Profesor" class="nav-top-item">Profesor</a> 
			                <ul> 
			                    <li><a href="index.php?controlador=ctrProfesores&accion=regProfesores">Registro </a></li> 
			                    <li><a href="index.php?controlador=ctrProfesores&accion=modProfesores">Modificar</a></li> 
			                    <li><a href="index.php?controlador=ctrProfesores&accion=asigProfesores">Asignar/Reasignar</a></li> 
			                </ul> 
			            </li> 
			            <li> 
			                <a href="#"  id="Clientes" class="nav-top-item">Clientes</a> 
			                <ul> 
			                    <li><a href="index.php?controlador=ctrClientes&accion=regClientes">Registro </a></li> 
			                    <li><a href="index.php?controlador=ctrClientes&accion=modClientes">Modificar</a></li> 
			                    <li><a href="index.php?controlador=ctrClientes&accion=contClientes">Matricular</a></li> 
			                    <li><a href="index.php?controlador=ctrClientes&accion=bonoClientes">Bonos</a></li> 
			                    <li><a href="index.php?controlador=ctrClientes&accion=verClasescanceladas">Clases canceladas</a></li> 
			                </ul> 
			            </li>
					</ul> <!-- End #main-nav --> 
						
				</div>
			</div> <!-- End #sidebar -->
			
			<div id="main-content"> <!-- Main Content Section with everything --> 
        		<div id="AccionesUser"> 
                	<noscript> <!-- Show a notification if the user has disabled javascript -->
                        <div>
                            Javascript no esta activo o no es soportado por tu navegador. Por favor <a href="http://browsehappy.com/" title="Actualizar a otro navegador">actualiza</a> tu navegador o <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Activar ajavascript en el navegador">activa</a> Javascript en tu navegador.
                    	</div>
                	</noscript> 
 
	                <!-- Page Head --> 
	                <h2>Bienvenido Administrador Uno Administrador Uno.</h2> 
					<p id="page-intro">Que deseas hacer?</p> 
 
                	<ul class="shortcut-buttons-set"> 
					                    	                        													
					
                </ul> 
			</div>			<div class="clear"></div> <!-- End .clear --> 
			
			<div class="content-box"><!-- Start Content Box --> 
				
				<div class="content-box-header"> 
					
					<h3>Panel Principal</h3> 
					
					<ul class="content-box-tabs"> 
						<li><a href="#tab1" class="default-tab">Clases</a></li> 
						<!-- href must be unique and match the id of target div --> 
						<li><a href="#tab2">Agenda</a></li> 
					</ul> 
					
					<div class="clear"></div> 
					
				</div> <!-- End .content-box-header --> 
				
				<div class="content-box-content"> 
					
				  <div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab --> 
						                        <div class="notification success png_bg"> 
                            <a class="close" href="#"><img alt="close" title="Close this notification" src="vista/images/icons/cross_grey_small.png"></a> 
                            <div> 
                                Genial, no hay clases en conflicto de confirmaci&oacute;n.
                            </div> 
                        </div> 
					  <div id="messages" style="display: none">

		<h3>0 Clase(s) en conflicto!</h3> 

        <script type="text/javascript">

		$(document).ready(function(){

			$(".form_send").each(function(){

				ob = $(this);

				$(this).submit(function(){				

					$(this).fadeOut();

					$.ajax({

						type: "POST",

						url: "index.php?controlador=ctrClientes&accion=confirmClase",

						data: $(this).serialize(),

						success: function(msg){

						}

					});

					

					$(".close").click(function(){

						document.location.reload();						   

					});

					return false;

				})

				$(this).find(".remove-link").each(function(){

					$(this).click(function(){

						$(this).parent().parent(".form_send").find("#option_"+$(this).attr("Id")).val("2");

						$.ajax({

							type: "POST",

							url: "index.php?controlador=ctrClientes&accion=confirmClase",

							data: $(this).parent().parent(".form_send").serialize()+"&confirm=QUxVTU5P"

						});

						$(".close").click(function(){

							document.location.reload();						   

						});

						$(this).parent().parent(".form_send").fadeOut();

						return false;

					})

				})

			})

		})

    </script>

			</div>                      					  <table width="100%"> 
						  <thead> 
							  <tr> 
							     <th colspan="6">&Uacute;ltimas 10 clases confirmadas</th> 
						      </tr> 
                              <tr> 
							     <th>Area</th> 
							     <th>Materia</th> 
							     <th>Fecha</th> 
							     <th>Horas</th> 
							     <th>Profesor</th> 
							     <th>Observación</th> 
						      </tr> 
								
						  </thead> 
						  <tfoot> 
							  <tr> 
								  <td colspan="6"> 
									  <div class="clear"></div> 
								  </td> 
							  </tr> 
						  </tfoot> 
						  <tbody> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-04-27</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong> impartida pero eso fue el martes no ayer. No entiendo porque se cambio                                  </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-04-29</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong> conforme <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-03</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong> conforme <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-06</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong> conforme <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-10</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-09</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>ESO</td> 
								  <td>Ciencias de la naturaleza</td> 
								  <td>2011-05-09</td> 
								  <td>01:30:00</td> 
								  <td>María Gabriela</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>ESO</td> 
								  <td>Ciencias de la naturaleza</td> 
								  <td>2011-05-09</td> 
								  <td>01:30:00</td> 
								  <td>María Gabriela</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>ESO</td> 
								  <td>Ciencias de la naturaleza</td> 
								  <td>2011-05-18</td> 
								  <td>01:30:00</td> 
								  <td>María Gabriela</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong> Última clase con este cliente. Todo bien.                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-20</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          						  </tbody> 
							
					  </table> 
						
					</div> 
					<!-- End #tab1 --> 
					
					<div class="tab-content" id="tab2"> 
						<p> 
							<img src="vista/images/icons/info-loader.gif" alt="Loading" /> En construcci&oacute;n...
						</p> 
				  </div> 
			  </div> 
			</div> 
	    	<!--<div class="content-box column-left">
				<div class="content-box-header">
					<h3>&Uacute;ltimo importe pagado</h3>
				</div>
				<div class="content-box-content">
					<div class="tab-content default-tab">
						<h4>Maecenas dignissim</h4>
						<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in porta lectus. Maecenas dignissim enim quis ipsum mattis aliquet. Maecenas id velit et elit gravida bibendum. Duis nec rutrum lorem. Donec egestas metus a risus euismod ultricies. Maecenas lacinia orci at neque commodo commodo.
						</p>
					</div>      
				</div>
			</div>
			
			<div class="content-box column-right">
				<div class="content-box-header">
					<h3>Importe pendiente de pago</h3>
				</div>
				<div class="content-box-content">
					<div class="tab-content default-tab">
						<h4>This box is closed by default</h4>
						<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in porta lectus. Maecenas dignissim enim quis ipsum mattis aliquet. Maecenas id velit et elit gravida bibendum. Duis nec rutrum lorem. Donec egestas metus a risus euismod ultricies. Maecenas lacinia orci at neque commodo commodo.
						</p>
					</div>     
				</div>
			</div> --> 
            <div class="clear"></div> 
 
				  <div id="footer"> 
				<small> 
						&#169; Copyright 2011 Centro Formativo Internacional | Powered by <a target="_blank" href="http://www.isourceltda.net">&amp;Source Ltda</a> | <a href="#">Arriba</a> 
				</small> 
			</div>	</div></body> 
</html> 