<?php Load::lib("html") ?>
	<div id="AccionesUser">
		<h2>Bienvenido Administrador Uno Administrador Uno.</h2>
		<p id="page-intro">
			Que deseas hacer?
		</p>

		<ul class="shortcut-buttons-set">

		</ul>
	</div>
	<div class="clear"></div>
	<div class="content-box">
		<!-- Start Content Box -->
		<div class="content-box-header">
			<h3>Panel Principal</h3>
			<ul class="content-box-tabs">
				<li>
					<a href="#tab1" class="default-tab">Clases</a>
				</li>
				<!-- href must be unique and match the id of target div -->
				<li>
					<a href="#tab2">Agenda</a>
				</li>
			</ul>
			<div class="clear"></div>
		</div>

		<div class="content-box-content">

			<div class="tab-content default-tab" id="tab1">
				<!-- This is the target div. id must match the href of this div's tab -->
				<div class="notification success png_bg">
					<a class="close" href="#">
						<?= Html::imagen("pruebas/icons/cross_grey_small.png") ?>
					</a>
					<div>
						Genial, no hay clases en conflicto de confirmaci&oacute;n.
					</div>
				</div>
				<div id="messages" style="display: none">
					<h3>0 Clase(s) en conflicto!</h3>
				</div>
				<table width="100%">
					<thead>
						<tr>
							<th colspan="6">&Uacute;ltimas 10 clases confirmadas</th>
						</tr>
						<tr>
							<th>Area</th>
							<th>Materia</th>
							<th>Fecha</th>
							<th>Horas</th>
							<th>Profesor</th>
							<th>Observación</th>
						</tr>

					</thead>
					<tfoot>
						<tr>
							<td colspan="6">
							<div class="clear">
							</div>
							</td>
						</tr>
					</tfoot>
					<tbody>
						<tr>
							<td>Primaria</td>
							<td>Matemáticas.</td>
							<td>2011-04-27</td>
							<td>01:30:00</td>
							<td>Marisa Cruz</td>
							<td>
							<strong>Obs alumno:</strong>
							<br />
							<strong>Obs Profesor:</strong> impartida pero eso fue el martes no ayer. No entiendo porque se cambio
							</td>
						</tr>
						<tr>
							<td>Primaria</td>
							<td>Matemáticas.</td>
							<td>2011-04-29</td>
							<td>01:30:00</td>
							<td>Marisa Cruz</td>
							<td>
							<strong>Obs alumno:</strong> conforme
							<br />
							<strong>Obs Profesor:</strong>
							</td>
						</tr>
						<tr>
							<td>Primaria</td>
							<td>Matemáticas.</td>
							<td>2011-05-03</td>
							<td>01:30:00</td>
							<td>Marisa Cruz</td>
							<td>
							<strong>Obs alumno:</strong> conforme
							<br />
							<strong>Obs Profesor:</strong>
							</td>
						</tr>
						<tr>
							<td>Primaria</td>
							<td>Matemáticas.</td>
							<td>2011-05-06</td>
							<td>01:30:00</td>
							<td>Marisa Cruz</td>
							<td>
							<strong>Obs alumno:</strong> conforme
							<br />
							<strong>Obs Profesor:</strong>
							</td>
						</tr>
						<tr>
							<td>Primaria</td>
							<td>Matemáticas.</td>
							<td>2011-05-10</td>
							<td>01:30:00</td>
							<td>Marisa Cruz</td>
							<td>
							<strong>Obs alumno:</strong>
							<br />
							<strong>Obs Profesor:</strong>
							</td>
						</tr>
						<tr>
							<td>Primaria</td>
							<td>Matemáticas.</td>
							<td>2011-05-09</td>
							<td>01:30:00</td>
							<td>Marisa Cruz</td>
							<td>
							<strong>Obs alumno:</strong>
							<br />
							<strong>Obs Profesor:</strong>
							</td>
						</tr>
						<tr>
							<td>ESO</td>
							<td>Ciencias de la naturaleza</td>
							<td>2011-05-09</td>
							<td>01:30:00</td>
							<td>María Gabriela</td>
							<td>
							<strong>Obs alumno:</strong>
							<br />
							<strong>Obs Profesor:</strong>
							</td>
						</tr>
						<tr>
							<td>ESO</td>
							<td>Ciencias de la naturaleza</td>
							<td>2011-05-09</td>
							<td>01:30:00</td>
							<td>María Gabriela</td>
							<td>
							<strong>Obs alumno:</strong>
							<br />
							<strong>Obs Profesor:</strong>
							</td>
						</tr>
						<tr>
							<td>ESO</td>
							<td>Ciencias de la naturaleza</td>
							<td>2011-05-18</td>
							<td>01:30:00</td>
							<td>María Gabriela</td>
							<td>
							<strong>Obs alumno:</strong>
							<br />
							<strong>Obs Profesor:</strong> Última clase con este cliente. Todo bien.
							</td>
						</tr>
						<tr>
							<td>Primaria</td>
							<td>Matemáticas.</td>
							<td>2011-05-20</td>
							<td>01:30:00</td>
							<td>Marisa Cruz</td>
							<td>
							<strong>Obs alumno:</strong>
							<br />
							<strong>Obs Profesor:</strong>
							</td>
						</tr>
					</tbody>

				</table>

			</div>
			<!-- End #tab1 -->

			<div class="tab-content" id="tab2">
				<p>
					<img src="vista/images/icons/info-loader.gif" alt="Loading" />
					En construcci&oacute;n...
				</p>
			</div>
		</div>
	</div>
	<div class="clear">
	</div>
