<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>
		<?php Load::lib("html") ?>
		<?= View::helpers("menu") ?>
		<?php
		
			$menu = new Menu("ajax");
			
			$menu -> logotipo("pruebas/inicio","quinielitas.png","AmecaMX");
			$menu -> cerrar("Cerrar Sesión","pruebas/cerrar");
			
			$menu -> seccion("Cuenta","pruebas/cuenta");
			
			$menu -> link("Mi Perfil","pruebas/perfil");
			$menu -> link("Avatars","pruebas/avatars");
			$menu -> link("Notificaciones","pruebas/notificaciones");
			$menu -> link("Configuración","pruebas/configuracion");
			
			$menu -> seccion("Mis Amigos","pruebas/amigos");
			
			$menu -> link("Compas","pruebas/compas");
			
		?>
		<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
		<title>Kumbia Amecasoft (Jquery/Ajax)</title>
		<link rel="shortcut icon" href="<?= PUBLIC_PATH ?>favicon.ico" type="image/x-icon" /> 
		
		<?= stylesheet_link_tag('kusocial/reset') ?>
		<?= stylesheet_link_tag('kusocial') ?>
		<?= stylesheet_link_tag('kusocial/invalid') ?>
        
        <?= View::partial("jquery",false,'template: ui-darkness'); ?>
        <?= javascript_include_tag('pruebas/browsers') ?>
        <?= javascript_include_tag('kusocial') ?>
	</head>
	<body>
		<!-- Wrapper for the radial gradient background -->
		<div id="sidebar">
			<div id="sidebar-wrapper">
				<!-- Sidebar with logo and menu -->
				<!-- Logo (221px wide) -->
				<?= $menu -> logotipo() ?>
				<!-- Sidebar Profile links -->
				<div id="profile">
					<div style="float: left;">
						<?php
							//Session::set("usuario_avatar","http://graph.facebook.com/906075301/picture");
							//Session::set("usuario_nombres","Ramiro Alonso");
							//Session::set("usuario_apellidos","Vera Contreras");
							if(Session::get("usuario_avatar")){
								echo Html::imagen(Session::get("usuario_avatar"),Session::get("usuario_nombres"),50,50,"id: avatar");
							}
							else{
								echo Html::imagen("navatar.gif",Session::get("usuario_nombres"),50,50,"id: avatar");
							}
						?>
					</div>
					<div id="username">
						<?php
							if(Session::get("usuario_nombres") && Session::get("usuario_apellidos")){
								echo Session::get("usuario_nombres")."<br>".Session::get("usuario_apellidos");
							}
							else{
								echo "Usuario<br>Desconocido";
							}
						?>
					</div>
					<div id="link">
						<i><?= $menu -> cerrar() ?></i>
					</div>
				</div>
				<?= $menu -> html(); ?>
			</div>
		</div> <!-- End #sidebar -->
		<div id="main-content">
			<?php View::content(); ?>
			<div id="footer">
				<small>
					&#169; Copyright 2011 KuSocial | Desarrollado por 
					<a target="_blank" href="http://www.www.amecasoft.com.mx">Amecasoft S.A. de C.V.</a> |
					<a href="#">Arriba</a>
				</small>
			</div>
		</div>
	</body>
</html>