<!-- Load the Google AJAX API Loader -->
<script type="text/javascript" src="http://www.google.com/jsapi"></script>

<!-- Load the Google Friend Connect javascript library. -->
<script type="text/javascript">
	google.load('friendconnect', '0.8');
</script>

<!-- Initialize the Google Friend Connect OpenSocial API. -->
<script type="text/javascript">
	google.friendconnect.container.setParentUrl('/' /* location of rpc_relay.html and canvas.html */);
	google.friendconnect.container.initOpenSocialApi({
	  site: '13534367266835928207',
	  onload: function(securityToken) { /* your callback, which is passed a security token */ }
	});
	
	google.friendconnect.renderSignInButton({id:"google-login",style:'long'});
</script>
<div class="services">
<fb:login-button length="long" onlogin="auth_using_fb();"></fb:login-button>
<div id="google-login">a</div>
</div>
<div id="AccionesUser"> 
                <noscript> <!-- Show a notification if the user has disabled javascript -->
                        <div>
                            Javascript no esta activo o no es soportado por tu navegador. Por favor <a href="http://browsehappy.com/" title="Actualizar a otro navegador">actualiza</a> tu navegador o <a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Activar ajavascript en el navegador">activa</a> Javascript en tu navegador.
                    </div>
                </noscript> 
 
                <!-- Page Head --> 
                <h2>Bienvenido Administrador Uno Administrador Uno.</h2> 
  <p id="page-intro">Que deseas hacer?</p> 
 
                <ul class="shortcut-buttons-set"> 
					                    	                        													
					
                </ul> 
			</div>			<div class="clear"></div> <!-- End .clear --> 
			
			<div class="content-box"><!-- Start Content Box --> 
				
				<div class="content-box-header"> 
					
					<h3>Panel Principal</h3> 
					
					<ul class="content-box-tabs"> 
						<li><a href="#tab1" class="default-tab">Clases</a></li> 
						<!-- href must be unique and match the id of target div --> 
						<li><a href="#tab2">Agenda</a></li> 
					</ul> 
					
					<div class="clear"></div> 
					
				</div> <!-- End .content-box-header --> 
				
				<div class="content-box-content"> 
					
				  <div class="tab-content default-tab" id="tab1"> <!-- This is the target div. id must match the href of this div's tab --> 
						                        <div class="notification success png_bg"> 
                            <a class="close" href="#"><img alt="close" title="Close this notification" src="vista/images/icons/cross_grey_small.png"></a> 
                            <div> 
                                Genial, no hay clases en conflicto de confirmaci&oacute;n.
                            </div> 
                        </div> 
					  <div id="messages" style="display: none">

		<h3>0 Clase(s) en conflicto!</h3> 
</div>
						<table width="100%"> 
						  <thead> 
							  <tr> 
							     <th colspan="6">&Uacute;ltimas 10 clases confirmadas</th> 
						      </tr> 
                              <tr> 
							     <th>Area</th> 
							     <th>Materia</th> 
							     <th>Fecha</th> 
							     <th>Horas</th> 
							     <th>Profesor</th> 
							     <th>Observación</th> 
						      </tr> 
								
						  </thead> 
						  <tfoot> 
							  <tr> 
								  <td colspan="6"> 
									  <div class="clear"></div> 
								  </td> 
							  </tr> 
						  </tfoot> 
						  <tbody> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-04-27</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong> impartida pero eso fue el martes no ayer. No entiendo porque se cambio                                  </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-04-29</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong> conforme <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-03</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong> conforme <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-06</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong> conforme <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-10</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-09</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>ESO</td> 
								  <td>Ciencias de la naturaleza</td> 
								  <td>2011-05-09</td> 
								  <td>01:30:00</td> 
								  <td>María Gabriela</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>ESO</td> 
								  <td>Ciencias de la naturaleza</td> 
								  <td>2011-05-09</td> 
								  <td>01:30:00</td> 
								  <td>María Gabriela</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>ESO</td> 
								  <td>Ciencias de la naturaleza</td> 
								  <td>2011-05-18</td> 
								  <td>01:30:00</td> 
								  <td>María Gabriela</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong> Última clase con este cliente. Todo bien.                                   </td> 
							  </tr> 
                          							  <tr> 
								  <td>Primaria</td> 
								  <td>Matemáticas.</td> 
								  <td>2011-05-20</td> 
								  <td>01:30:00</td> 
								  <td>Marisa Cruz</td> 
								  <td><strong>Obs alumno:</strong>  <br /> 
                                  <strong>Obs Profesor:</strong>                                   </td> 
							  </tr> 
                          						  </tbody> 
							
					  </table> 
						
					</div> 
					<!-- End #tab1 --> 
					
					<div class="tab-content" id="tab2"> 
						<p> 
							<img src="vista/images/icons/info-loader.gif" alt="Loading" /> En construcci&oacute;n...
						</p> 
				  </div> 
			  </div> 
			</div> 
	    	<!--<div class="content-box column-left">
				<div class="content-box-header">
					<h3>&Uacute;ltimo importe pagado</h3>
				</div>
				<div class="content-box-content">
					<div class="tab-content default-tab">
						<h4>Maecenas dignissim</h4>
						<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in porta lectus. Maecenas dignissim enim quis ipsum mattis aliquet. Maecenas id velit et elit gravida bibendum. Duis nec rutrum lorem. Donec egestas metus a risus euismod ultricies. Maecenas lacinia orci at neque commodo commodo.
						</p>
					</div>      
				</div>
			</div>
			
			<div class="content-box column-right">
				<div class="content-box-header">
					<h3>Importe pendiente de pago</h3>
				</div>
				<div class="content-box-content">
					<div class="tab-content default-tab">
						<h4>This box is closed by default</h4>
						<p>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in porta lectus. Maecenas dignissim enim quis ipsum mattis aliquet. Maecenas id velit et elit gravida bibendum. Duis nec rutrum lorem. Donec egestas metus a risus euismod ultricies. Maecenas lacinia orci at neque commodo commodo.
						</p>
					</div>     
				</div>
			</div> --> 
            <div class="clear"></div> 